AllCops:
  Exclude:
    - db/**/*
    - test/**/*
    - tmp/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

MethodLength:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Performance/UnfreezeString:
  Enabled: false
