# doc_seqs_sku_number:
#   db_sequence_name: doc_seqs_sku_number
#   data_type: :integer
#   table: mr_skus
#   column: sku_number
dummy_invoice:
  db_sequence_name: doc_seqs_inv
  data_type: :string
  prefix: INV
  digit_length: 7
  table: invoices
  column: invoice_ref